server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gangnam
    password: gangnam
    username: gangnam
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: none




